travis:
  secure:
    BINSTAR_TOKEN: URryv2Dvn3xR0CSH8h4A8ukw08O57KY9gM39/qIzNsOdgprVwdXvFb8kcbArP5R+xT/Cmz8yaipXcz+eRKTlseytCSuhjYRbIXrVx2nAt/cH1r/aM4BgiaT/Eh8etlMwlQfvfziB3ejqZ/+g9bzRqMg1bRiFYaPGDScLCOdzdCJ8r5L16PF4T7yycyuk6hpuV7hRq+dxPN3YPIWMtq6TBbm4E45jyMX+TAGOGj81BcjaKRRjZi5MBtz5Ul7K8Dyvadu3KrE0Wlof5tP3bpHM/3bjLBWpNsK4kGcX1mAr6HgmF8vKLmeCnu5SeMwXFUc+KEnymaSln1P+GDrPBBnb1hbVN768IUOOaOTS/mIemvxBqqgdxdAMmKhvJPHxwVg2CmCupoRxHjJlRUneFbo10KNHkigYCxY1QdKb9THnmmhMOVH4nPpVK+PobzPBtUTvzCwl5XbE9DvgEax1mAbklscK9U8zgsnLaWdGGkniu86vkK+CtSFGKnMLOceqx0u0x8nR2zlIkpCmjEeiVh8qCol44TCrFPQROA7zobNUZGCpz96ZDfc7qclghlXQAAbn24WagwAwAqWnbGJLO5YJbuVSF+Dehg4qiK3jgbbFctlp/GiToFFa4CHnGvGTQ9N/a6SMEUPUVhyZjMnIQ6MSweNGvOfFdWugD8yZdXAjUzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
